/**
 * Markdown → DOCX Converter
 *
 * Converts markdown content to an editable .docx file using docx-js.
 * Produces valid OOXML that opens cleanly in Word, Google Docs, and LibreOffice.
 *
 * Critical rules followed (from DOCX skill):
 * - Set page size explicitly (A4)
 * - Never use \n — use separate Paragraph elements
 * - Never use unicode bullets — use LevelFormat.BULLET numbering config
 * - PageBreak must be inside a Paragraph
 * - ImageRun requires `type` parameter
 * - Tables need dual widths (columnWidths + cell width, both in DXA)
 * - Always use WidthType.DXA — never PERCENTAGE
 * - Use ShadingType.CLEAR — never SOLID
 * - Always add cell margins
 * - Override built-in styles with exact IDs ("Heading1", "Heading2")
 * - Include outlineLevel in heading styles
 * - Colors WITHOUT # prefix
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  ImageRun,
  Header,
  Footer,
  HeadingLevel,
  AlignmentType,
  LevelFormat,
  BorderStyle,
  WidthType,
  ShadingType,
  PageNumber,
  ExternalHyperlink,
} from "docx";
import { marked, type Token, type Tokens } from "marked";
import { COLORS, DOCX_PAGE, DOCX_FONT_SIZES, DOCX_SPACING, FONTS } from "./constants";
import { CHART_ASPECT_RATIO } from "./chart-renderer";
import { extractAndRenderCharts } from "./extract-charts";
import { resolveExportOptions, type ExportInput } from "./types";

/** On-page chart display width in points (docx `transformation` units). */
const CHART_DISPLAY_WIDTH = 500;
import { preprocessContent } from "./preprocess-content";

// ─── Main Export ────────────────────────────────────────────────────────────

/**
 * Convert a markdown string to an editable DOCX and return it as a Buffer.
 *
 * @param content  Markdown source (may contain json-chart blocks and tables).
 * @param options  A title string, or an {@link ExportOptions} object.
 */
export async function markdownToDocx(content: string, options?: ExportInput): Promise<Buffer> {
  const opts = resolveExportOptions(options, { title: "Document" });

  // 1. Pre-process: convert custom blocks to markdown
  const preprocessed = preprocessContent(content);

  // 2. Extract and render charts
  const { cleanMarkdown, charts } = await extractAndRenderCharts(preprocessed, {
    strictCharts: opts.strictCharts,
  });

  // 3. Parse markdown to tokens
  const tokens = marked.lexer(cleanMarkdown);

  // 4. Convert tokens to docx paragraph/table elements
  const children = await tokensToDocxElements(tokens, charts);

  const title = opts.title;

  // 5. Build document
  const doc = new Document({
    title,
    ...(opts.author ? { creator: opts.author } : {}),
    description: "Generated by mdforge",
    styles: {
      default: {
        document: {
          run: { font: FONTS.docx.body, size: DOCX_FONT_SIZES.body, color: COLORS.ink80.docx },
        },
      },
      paragraphStyles: [
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: DOCX_FONT_SIZES.h1, bold: true, font: FONTS.docx.body, color: COLORS.ink100.docx },
          paragraph: { spacing: { before: DOCX_SPACING.headingBefore, after: DOCX_SPACING.headingAfter }, outlineLevel: 0 },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: DOCX_FONT_SIZES.h2, bold: true, font: FONTS.docx.body, color: COLORS.ink100.docx },
          paragraph: { spacing: { before: DOCX_SPACING.headingBefore, after: DOCX_SPACING.headingAfter }, outlineLevel: 1 },
        },
        {
          id: "Heading3",
          name: "Heading 3",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: DOCX_FONT_SIZES.h3, bold: true, font: FONTS.docx.body, color: COLORS.ink100.docx },
          paragraph: { spacing: { before: DOCX_SPACING.headingBefore, after: DOCX_SPACING.headingAfter }, outlineLevel: 2 },
        },
      ],
    },
    numbering: {
      config: [
        {
          reference: "bullets",
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: "\u2022",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: DOCX_SPACING.listIndent, hanging: DOCX_SPACING.listHanging } } },
            },
            {
              level: 1,
              format: LevelFormat.BULLET,
              text: "\u25E6",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: DOCX_SPACING.listIndent * 2, hanging: DOCX_SPACING.listHanging } } },
            },
          ],
        },
        {
          reference: "numbers",
          levels: [
            {
              level: 0,
              format: LevelFormat.DECIMAL,
              text: "%1.",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: DOCX_SPACING.listIndent, hanging: DOCX_SPACING.listHanging } } },
            },
            {
              level: 1,
              format: LevelFormat.DECIMAL,
              text: "%2.",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: DOCX_SPACING.listIndent * 2, hanging: DOCX_SPACING.listHanging } } },
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: DOCX_PAGE.width, height: DOCX_PAGE.height },
            margin: {
              top: DOCX_PAGE.margin,
              right: DOCX_PAGE.margin,
              bottom: DOCX_PAGE.margin,
              left: DOCX_PAGE.margin,
            },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: title, font: FONTS.docx.body, size: 16, color: COLORS.ink40.docx }),
                ],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: "Page ", font: FONTS.docx.body, size: 16, color: COLORS.ink40.docx }),
                  new TextRun({ children: [PageNumber.CURRENT], font: FONTS.docx.body, size: 16, color: COLORS.ink40.docx }),
                ],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  // 5. Pack to buffer
  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}

// ─── Token Processing ───────────────────────────────────────────────────────

async function tokensToDocxElements(
  tokens: Token[],
  charts: Map<string, Buffer>
): Promise<(Paragraph | Table)[]> {
  const elements: (Paragraph | Table)[] = [];

  for (const token of tokens) {
    const result = await tokenToElements(token, charts);
    elements.push(...result);
  }

  return elements;
}

async function tokenToElements(
  token: Token,
  charts: Map<string, Buffer>
): Promise<(Paragraph | Table)[]> {
  switch (token.type) {
    case "heading": {
      const t = token as Tokens.Heading;
      const level = t.depth === 1 ? HeadingLevel.HEADING_1
        : t.depth === 2 ? HeadingLevel.HEADING_2
        : HeadingLevel.HEADING_3;

      return [
        new Paragraph({
          heading: level,
          children: inlineTokensToRuns(t.tokens),
        }),
      ];
    }

    case "paragraph": {
      const t = token as Tokens.Paragraph;

      // Check for chart placeholder
      const plainText = getPlainText(t.tokens);
      const chartMatch = plainText.match(/\[CHART:(\w+)\]/);
      if (chartMatch && chartMatch[1]) {
        const chartBuffer = charts.get(chartMatch[1]);
        if (chartBuffer) {
          return [
            new Paragraph({
              children: [
                new ImageRun({
                  type: "png",
                  data: chartBuffer,
                  // Display box in points. The source bitmap is far higher
                  // resolution (see CHART_RENDER_SCALE), so shrinking it here is
                  // what makes it crisp. Height derived from the true aspect
                  // ratio to avoid any distortion.
                  transformation: {
                    width: CHART_DISPLAY_WIDTH,
                    height: Math.round(CHART_DISPLAY_WIDTH / CHART_ASPECT_RATIO),
                  },
                  altText: { title: "Chart", description: "Data visualization", name: "chart" },
                }),
              ],
              spacing: { before: 120, after: 120 },
            }),
          ];
        }
        return [];
      }

      return [
        new Paragraph({
          children: inlineTokensToRuns(t.tokens),
          spacing: { after: DOCX_SPACING.paragraphAfter },
        }),
      ];
    }

    case "list": {
      const t = token as Tokens.List;
      const reference = t.ordered ? "numbers" : "bullets";
      const items: Paragraph[] = [];

      for (const item of t.items) {
        // Handle task list items (checklists)
        const prefix = item.task
          ? (item.checked ? "[x] " : "[ ] ")
          : "";

        const runs = inlineTokensToRuns(item.tokens);
        if (prefix) {
          runs.unshift(new TextRun({ text: prefix, font: FONTS.docx.mono, size: DOCX_FONT_SIZES.body, color: COLORS.ink60.docx }));
        }

        items.push(
          new Paragraph({
            numbering: { reference, level: 0 },
            children: runs,
            spacing: { after: 60 },
          })
        );
      }
      return items;
    }

    case "table": {
      const t = token as Tokens.Table;
      return [buildTable(t)];
    }

    case "code": {
      const t = token as Tokens.Code;
      const lines = t.text.split("\n");
      const paragraphs: Paragraph[] = [];

      for (const line of lines) {
        paragraphs.push(
          new Paragraph({
            children: [
              new TextRun({
                text: line || " ", // empty lines need at least a space
                font: FONTS.docx.mono,
                size: DOCX_FONT_SIZES.code,
                color: COLORS.ink80.docx,
              }),
            ],
            shading: { fill: COLORS.bgSurface2.docx, type: ShadingType.CLEAR },
            spacing: { after: 0, line: 280 },
          })
        );
      }

      // Add spacing after code block
      paragraphs.push(new Paragraph({ spacing: { before: 120 }, children: [] }));
      return paragraphs;
    }

    case "blockquote": {
      const t = token as Tokens.Blockquote;
      const paragraphs: Paragraph[] = [];

      for (const child of t.tokens) {
        if (child.type === "paragraph") {
          const p = child as Tokens.Paragraph;
          paragraphs.push(
            new Paragraph({
              children: inlineTokensToRuns(p.tokens, { italic: true, color: COLORS.ink60.docx }),
              indent: { left: 400 },
              border: {
                left: { style: BorderStyle.SINGLE, size: 18, color: COLORS.accent.docx, space: 8 },
              },
              spacing: { after: 80 },
            })
          );
        }
      }
      return paragraphs;
    }

    case "hr": {
      return [
        new Paragraph({
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 4, color: COLORS.borderSubtle.docx, space: 4 },
          },
          spacing: { before: 200, after: 200 },
          children: [],
        }),
      ];
    }

    case "space": {
      return [new Paragraph({ spacing: { before: 60 }, children: [] })];
    }

    default: {
      if ("text" in token && typeof (token as any).text === "string") {
        return [
          new Paragraph({
            children: [new TextRun({ text: (token as any).text, color: COLORS.ink80.docx })],
            spacing: { after: DOCX_SPACING.paragraphAfter },
          }),
        ];
      }
      return [];
    }
  }
}

// ─── Inline Token → TextRun Conversion ──────────────────────────────────────

interface RunOverrides {
  bold?: boolean;
  italic?: boolean;
  color?: string;
}

/** A paragraph child: either a styled text run or a real hyperlink. */
type InlineChild = TextRun | ExternalHyperlink;

/**
 * Convert inline markdown tokens into docx paragraph children.
 *
 * Bold/italic state is threaded through nested tokens (so `**bold _italic_**`
 * and `_**italic bold**_` both keep both styles), codespans and links are
 * handled at any depth, and links become real clickable `ExternalHyperlink`
 * elements rather than dead underlined text.
 */
function inlineTokensToRuns(
  tokens: Token[] | undefined,
  overrides: RunOverrides = {},
): InlineChild[] {
  if (!tokens) return [];
  const out: InlineChild[] = [];

  const runColor = () =>
    overrides.color ?? (overrides.bold ? COLORS.ink100.docx : COLORS.ink80.docx);

  for (const t of tokens) {
    switch (t.type) {
      case "text": {
        const tt = t as Tokens.Text;
        if ("tokens" in tt && Array.isArray(tt.tokens) && tt.tokens.length > 0) {
          out.push(...inlineTokensToRuns(tt.tokens, overrides));
        } else {
          out.push(
            new TextRun({
              text: tt.text,
              bold: overrides.bold,
              italics: overrides.italic,
              color: runColor(),
            }),
          );
        }
        break;
      }
      case "strong": {
        const tt = t as Tokens.Strong;
        out.push(...inlineTokensToRuns(tt.tokens, { ...overrides, bold: true }));
        break;
      }
      case "em": {
        const tt = t as Tokens.Em;
        out.push(...inlineTokensToRuns(tt.tokens, { ...overrides, italic: true }));
        break;
      }
      case "codespan": {
        const tt = t as Tokens.Codespan;
        out.push(
          new TextRun({
            text: tt.text,
            font: FONTS.docx.mono,
            size: DOCX_FONT_SIZES.code,
            color: COLORS.accent.docx,
            shading: { fill: COLORS.bgSurface2.docx, type: ShadingType.CLEAR },
          }),
        );
        break;
      }
      case "link": {
        const tt = t as Tokens.Link;
        const children = inlineTokensToRuns(tt.tokens, {
          ...overrides,
          color: COLORS.accent.docx,
        }).filter((c): c is TextRun => c instanceof TextRun);
        const underlined = children.length > 0
          ? children
          : [new TextRun({ text: tt.href, color: COLORS.accent.docx })];
        if (tt.href) {
          out.push(new ExternalHyperlink({ children: underlined, link: tt.href }));
        } else {
          out.push(...underlined);
        }
        break;
      }
      case "br": {
        out.push(new TextRun({ break: 1 }));
        break;
      }
      default: {
        if ("text" in t && typeof (t as any).text === "string") {
          out.push(new TextRun({ text: (t as any).text, bold: overrides.bold, color: runColor() }));
        }
        break;
      }
    }
  }

  return out;
}

// ─── Table Builder ──────────────────────────────────────────────────────────

function buildTable(table: Tokens.Table): Table {
  const numCols = table.header.length;
  // Calculate equal column widths that sum to content width
  const colWidth = Math.floor(DOCX_PAGE.contentWidth / numCols);
  const columnWidths = Array(numCols).fill(colWidth);
  // Adjust last column to ensure exact sum
  columnWidths[numCols - 1] = DOCX_PAGE.contentWidth - colWidth * (numCols - 1);

  const border = { style: BorderStyle.SINGLE, size: 1, color: COLORS.borderSubtle.docx };
  const borders = { top: border, bottom: border, left: border, right: border };
  const cellMargins = { top: 80, bottom: 80, left: 120, right: 120 };

  // Per-column alignment from the markdown table (`---:` = right, `:---:` = center).
  const cellAlign = (i: number) => {
    switch (table.align?.[i]) {
      case "right":
        return AlignmentType.RIGHT;
      case "center":
        return AlignmentType.CENTER;
      default:
        return AlignmentType.LEFT;
    }
  };

  // Header row
  const headerRow = new TableRow({
    children: table.header.map((cell, i) =>
      new TableCell({
        borders,
        width: { size: columnWidths[i], type: WidthType.DXA },
        shading: { fill: COLORS.bgSurface2.docx, type: ShadingType.CLEAR },
        margins: cellMargins,
        children: [
          new Paragraph({
            alignment: cellAlign(i),
            children: [
              new TextRun({
                text: getPlainText(cell.tokens),
                bold: true,
                size: DOCX_FONT_SIZES.small,
                color: COLORS.ink100.docx,
              }),
            ],
          }),
        ],
      })
    ),
  });

  // Data rows
  const dataRows = table.rows.map((row) =>
    new TableRow({
      children: row.map((cell, i) =>
        new TableCell({
          borders,
          width: { size: columnWidths[i], type: WidthType.DXA },
          margins: cellMargins,
          children: [
            new Paragraph({
              alignment: cellAlign(i),
              children: [
                new TextRun({
                  text: getPlainText(cell.tokens),
                  size: DOCX_FONT_SIZES.small,
                  color: COLORS.ink80.docx,
                }),
              ],
            }),
          ],
        })
      ),
    })
  );

  return new Table({
    width: { size: DOCX_PAGE.contentWidth, type: WidthType.DXA },
    columnWidths,
    rows: [headerRow, ...dataRows],
  });
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function getPlainText(tokens: Token[] | undefined): string {
  if (!tokens) return "";
  return tokens
    .map((t) => {
      if ("text" in t && typeof (t as any).text === "string") {
        if ("tokens" in t && Array.isArray((t as any).tokens)) {
          return getPlainText((t as any).tokens);
        }
        return (t as any).text;
      }
      if (t.type === "br") return " ";
      return "";
    })
    .join("");
}

// Chart extraction is shared with the PDF pipeline; see ./extract-charts.ts
